baseURL = "https://enzosantos.dev/"
locale = "pt"
title = "enzosantos.dev"

relativeURLs = true
canonifyURLs = true

defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true

summaryLength = 30

[build]
  writeStats = true

[module]
  [[module.imports]]
    path = "github.com/enzo-santos/hugo-noir"

[languages]
  [languages.pt]
    languageName = "Português"
    weight = 1
    contentDir = "content/pt"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "Enzo Santos"
location = "Belém, Pará, Brasil"
description = "Desenvolvedor Python. Engenheiro de software. Eu desenvolvo APIs, construo aplicações escaláveis e automatizo fluxos."
profile_image = "/images/profile.jpg"
github = "https://github.com/ezgrs"
github_username = "ezgrs"
email = "ezgrs.dev@gmail.com"
medium = "https://www.medium.com/@ezgrs"
linkedin = "https://www.linkedin.com/in/ezgrs"
linkedin_username = "ezgrs"

[menu]
  [[menu.main]]
    name = "Sobre"
    pageRef = "about"
    weight = 1
  [[menu.main]]
    name = "Experiência"
    pageRef = "experience"
    weight = 2
  [[menu.main]]
    name = "Projetos"
    pageRef = "projects"
    weight = 3
  [[menu.main]]
    name = "Blog"
    pageRef = "blogs"
    weight = 4
  [[menu.main]]
    name = "Contato"
    pageRef = "contact"
    weight = 5